#!/bin/bash
#PBS -l walltime=00:15:00
#PBS -l nodes=1:ppn=16
#PBS -N MPI
#PBS -o out-$PBS_JOBID.txt
#PBS -e err-$PBS_JOBID.txt

cd ${PBS_O_WORKDIR}

module load papi
#for size in 100 500 1000 2000 5000
#do
#		echo "N=${size}, M=${size}, cores=4"
#		aprun -n 4 -N 4 -d 1 ./MPI.exe  $size $size 
#done

for size in 100 500 1000 2000 5000
do
		echo "N=${size}, M=${size}, cores=4"
		aprun -n 8 -N 8 -d 1 ./MPI.exe  $size $size 
done

